# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
#6.times do |i|
#  Log.create nombre_usuario: "juan #{i}", ataque: true, tipo_ataque: 1, time_stamp_log: Time.zone.yesterday
#  Log.create nombre_usuario: "lucia #{i}", ataque: true, tipo_ataque: 2, time_stamp_log: Time.zone.yesterday
#  Log.create nombre_usuario: "jose #{i}", ataque: true, tipo_ataque: 3, time_stamp_log: Time.zone.yesterday
#  Log.create nombre_usuario: "maria #{i}", ataque: true, tipo_ataque: 4, time_stamp_log: Time.zone.yesterday
#end

Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion2' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: true, tipo_ataque: 'Operador Union', query_id: (Query.create nombre_query: 'SELECT', comando: "select gru_nombre, gru_cod, g_nivel from activo.grupo where gru_id=5 union select prov_ruc, prov_razon_social, 22 from activo proveedor where '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion2' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: true, tipo_ataque: 'Operador Union', query_id: (Query.create nombre_query: 'SELECT', comando: "select gru_nombre, gru_cod, g_nivel from activo.grupo where gru_id=5 union select prov_ruc, prov_razon_social, 22 from activo proveedor where '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion2' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: true, tipo_ataque: 'Operador Union', query_id: (Query.create nombre_query: 'SELECT', comando: "select gru_nombre, gru_cod, g_nivel from activo.grupo where gru_id=5 union select prov_ruc, prov_razon_social, 22 from activo proveedor where '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion2' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: true, tipo_ataque: 'Operador Union', query_id: (Query.create nombre_query: 'SELECT', comando: "select gru_nombre, gru_cod, g_nivel from activo.grupo where gru_id=5 union select prov_ruc, prov_razon_social, 22 from activo proveedor where '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion2' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: true, tipo_ataque: 'Operador Union', query_id: (Query.create nombre_query: 'SELECT', comando: "select gru_nombre, gru_cod, g_nivel from activo.grupo where gru_id=5 union select prov_ruc, prov_razon_social, 22 from activo proveedor where '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion2' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: true, tipo_ataque: 'Operador Union', query_id: (Query.create nombre_query: 'SELECT', comando: "select gru_nombre, gru_cod, g_nivel from activo.grupo where gru_id=5 union select prov_ruc, prov_razon_social, 22 from activo proveedor where '1'='1';").id


Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion3' , ip_log: '127.0.0.4' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: true, tipo_ataque: 'Piggy Backed', query_id: (Query.create nombre_query: 'SELECT - DROP', comando: "select *from gestion.ges_bodega where bod_nombre=''; DROP table gestion.ges_bodega --'AND pass='").id







Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion5' , ip_log: '127.0.0.6' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: true, tipo_ataque: 'Procedimiento Almacenado', query_id: (Query.create nombre_query: 'CREATE', comando: "CREATE OR REPLACE FUNCTION ejemplo() RETURNS integer AS $$ BEGIN select *from gestion.ges_usuario where usr_nombre = '' and usr_password = ''; drop table gestion.ges_usuario;--'END;").id




Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'CESAR' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id
Log.create nombre_base: 'prueba' , nombre_usuario: 'evaluacion1' , ip_log: '127.0.0.1' , time_stamp_log: Time.zone.today.beginning_of_day + 5.hour , ataque: true, tipo_ataque: 'Tautología', query_id: (Query.create nombre_query: 'SELECT', comando: "select * from gestion.ges_usuario where usr_nombre = 'GABRIELA' and usr_password = '' OR '1'='1';").id


Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 6.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 7.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 7.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 8.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 9.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 9.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 10.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.2' , time_stamp_log: Time.zone.today.beginning_of_day + 11.hour , ataque: false, tipo_ataque: ''
Log.create nombre_base: 'prueba' , nombre_usuario: 'cesar' , ip_log: '127.0.0.3' , time_stamp_log: Time.zone.today.beginning_of_day + 12.hour , ataque: false, tipo_ataque: ''